apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: findstore-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: findstore-service
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: camiloahm/findstore-service
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
